### ISSUE TITLE
login error

### ISSUE THREAD

**Issue by bluetyson** [mpigsley/sectors-without-number#82] opened 2018-02-01 21:29 UTC
When I signed up...either site....it said 'there has been an error' after doing so, even though got the email with no problem.

**Comment by mpigsley** [comment] 2018-02-01 21:38
@bluetyson did you use a login provider facebook/google or email/password?

**Comment by bluetyson** [comment] 2018-02-02 00:04
Email/password and Windows 10 Edge browser

**Comment by mpigsley** [comment] 2018-02-03 19:16
Wasn't able to reproduce the error. I'll leave this open for the time being. If I don't hear of others having problems then I'll close it at a later date.

**Comment by bluetyson** [comment] 2018-02-04 00:11
I'll see what happens on a different machine

**Comment by mpigsley** [comment] 2018-02-12 14:03
Closing since I haven't heard anything more from anyone.

**Closed by mpigsley** 2018-02-12 14:03 UTC
Labels: bug, in-progress
